### ISSUE TITLE
Splitted file

### ISSUE THREAD

**Issue by usherfiles** [JonathanxD/JsBlobDownloader#1]
Hey man, how are you? I really like your downloader, it's very handy but I want to ask you something that you may know how to resolve.
I'm on a shared hosting that don't allow us to change the php timeout value, so if I trigger a download with php, It will give me an corrupted file after 60 seconds due to this value, where the download stops and the file don't fail, it just stay there on the disk but incomplete...
I was trying to use your downloader but it fails with the same problem, but one idea did come to my mind, what if I download only a small file part (let's say 25 mb) and then append it to the blob, then start a new download from where it was (partial content download)  and do the same with the next part of the file, until the download is complete. 
But not trigger them at the same time, it's more like a serial download of chunks to avoid corrupted chunks on slow connections.
Do you think that is possible to download a file in chunks appending every 25mb to a blob or something like that?
Sorry if my english is bad, I'm from argentina.
Thanks for reading this <3

**Comment by jhrldev** [comment]
Hello, yes it is possible, I should have implemented this before, the solution is simple, it only need to retry if connection fails, but this project is very old and I haven't touched any JavaScript code for years, the implementation may take some time, maybe I release the update on this weekend. This is not the same as chunking, but may solve the problem (as long as the http server supports download resuming, but if doesn't, chunking would not work too)

**Comment by usherfiles** [comment]
oh god thanks <3

**Comment by usherfiles** [comment]
Oh god thanks.
Yeah, whatever works is fine for me. I can make a php script with resume option. The problem is  that with very large files (2GB and so, even 1GB) it times out and give you a corrupted file.
If it's not necesary to chunk  the file it's ok, maybe stop and resume the script every 58 seconds is fine or I don't know, do your magic <3 a thousand thanks <3

**Comment by jhrldev** [comment]
@usherfiles I have made what you requested :smile: , the feature used by the script to download files does not support resuming, so I added a `downloadChunked` function which you may provide the amount of chunks and it will download chunk-per-chunk, also if the download of a particular chunk is interrupted, the script will restart the download of this particular chunk. 

if you want to chunk by size, take a look in the new [README](https://github.com/JonathanxD/JSBlobDownloader/).

**Comment by usherfiles** [comment]
Oh man, you already have a place in my heart <3
I'm Having just One problem more, but I don't know if it's the script or my server.
I do have 10MB of internet connection. When I start downloading from a direct link (it isn't a php file yet) start normal but when it hit the third part of the download, the download slow down and it keeps going stuck at 100 kbps.
You can test it yourself here: https://edmcentralargentina.com/asdfg/
Start the download (it starts just fine) and then slows down itself and stuck the speed at 100kbps .
If you cancel the download and try with the direct link, it will be continue downloading at 100kbps.
I don't know what happened :( 
I changed the timeout because 10 secounds wasnt enough to download every part.
Can you test it from my website man? That would be amazing :)
